// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.15.8
// source: file_process_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileProcessing_ProcessFile_FullMethodName = "/file_processing.FileProcessing/ProcessFile"
)

// FileProcessingClient is the client API for FileProcessing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileProcessingClient interface {
	ProcessFile(ctx context.Context, in *ProcessFileReq, opts ...grpc.CallOption) (*ProcessFileRepl, error)
}

type fileProcessingClient struct {
	cc grpc.ClientConnInterface
}

func NewFileProcessingClient(cc grpc.ClientConnInterface) FileProcessingClient {
	return &fileProcessingClient{cc}
}

func (c *fileProcessingClient) ProcessFile(ctx context.Context, in *ProcessFileReq, opts ...grpc.CallOption) (*ProcessFileRepl, error) {
	out := new(ProcessFileRepl)
	err := c.cc.Invoke(ctx, FileProcessing_ProcessFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileProcessingServer is the server API for FileProcessing service.
// All implementations must embed UnimplementedFileProcessingServer
// for forward compatibility
type FileProcessingServer interface {
	ProcessFile(context.Context, *ProcessFileReq) (*ProcessFileRepl, error)
	mustEmbedUnimplementedFileProcessingServer()
}

// UnimplementedFileProcessingServer must be embedded to have forward compatible implementations.
type UnimplementedFileProcessingServer struct {
}

func (UnimplementedFileProcessingServer) ProcessFile(context.Context, *ProcessFileReq) (*ProcessFileRepl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessFile not implemented")
}
func (UnimplementedFileProcessingServer) mustEmbedUnimplementedFileProcessingServer() {}

// UnsafeFileProcessingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileProcessingServer will
// result in compilation errors.
type UnsafeFileProcessingServer interface {
	mustEmbedUnimplementedFileProcessingServer()
}

func RegisterFileProcessingServer(s grpc.ServiceRegistrar, srv FileProcessingServer) {
	s.RegisterService(&FileProcessing_ServiceDesc, srv)
}

func _FileProcessing_ProcessFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileProcessingServer).ProcessFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileProcessing_ProcessFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileProcessingServer).ProcessFile(ctx, req.(*ProcessFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FileProcessing_ServiceDesc is the grpc.ServiceDesc for FileProcessing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileProcessing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file_processing.FileProcessing",
	HandlerType: (*FileProcessingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessFile",
			Handler:    _FileProcessing_ProcessFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "file_process_service.proto",
}
